### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by HiroRin753** [HiroRin753/protospace-30569#1]
自身のProtoSpaceのURL
https://protospace-30569-85.herokuapp.com/

**Comment by tcamp1234** [comment]
HiroRin753 さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◎ユーザー詳細ページ機能
ユーザーの詳細ページには、そのユーザーの詳細情報と、そのユーザーが投稿したプロトタイプが表示されている
（ユーザーの投稿したプロトタイプが表示されておりません）
<img width="814" alt="スクリーンショット 2020-10-19 9 00 36" src="https://user-images.githubusercontent.com/64445215/96389348-ff1bdb80-11e9-11eb-94fc-33b459252044.png">

◎その他
他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる
（編集ページにアクセスできてしまいます）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tcamp1234** [comment]
HiroRin753さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
